# Configuration for MongoDB Exporter

mongodb:
  uri: ""

# Existing secret containing the MongoDB URI
# This secret should be created before deploying the MongoDB Exporter
existingSecret:
  name: "guestbook-mongodb-uri"
  key: "mongodb-uri"

# Service configuration
service:
  port: 9216
  type: ClusterIP

# ServiceMonitor configuration
serviceMonitor:
  enabled: true
  namespace: mongodb
  interval: 30s
  additionalLabels:
    release: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: prometheus-mongodb-exporter

# Resource limits and requests
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# ServiceMonitor selector
serviceMonitorSelector:
  matchLabels:
    release: kube-prometheus-stack
