# Config for Grafana
grafana:
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    # Set the host to the domain name of the Grafana instance based on ingress controller in local kind cluster
    hosts: 
      - "grafana.localhost"
    paths: ["/"]
    pathType: Prefix
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "true"
      searchNamespace: "monitoring"
      folderAnnotation: grafana_folder  # Optional: annotation to specify dashboard folder
      provider:
        foldersFromFilesStructure: true
