apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guestbook-backend.fullname" . }}-config
  labels:
    {{- include "guestbook-backend.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.deployment.port | quote }}
