apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guestbook-backend.fullname" . }}-mongodb
  labels:
    {{- include "guestbook-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.mongodb.auth.secretKeys.userPasswordKey }}: {{ .Values.mongodb.auth.password | toString | b64enc | quote }} 
