{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "guestbook-backend.fullname" . }}
  labels:
    {{- include "guestbook-backend.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusOperator }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/name: {{ include "guestbook-backend.name" . }}
spec:
  selector:
    matchLabels:
      {{- include "guestbook-backend.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
{{- end }}
